rootPageId: 1
base: "/"
baseVariants: {}
languages:
  - title: English
    enabled: true
    languageId: "0"
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ""
    flag: global
errorHandling:
  - errorCode: "404"
    errorHandler: Page
    errorContentSource: "t3://page?uid=4"
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
  NewsPlugin:
    type: Extbase
    limitToPages:
      - 41
    extension: News
    plugin: Pi1
    routes:
      - routePath: "/news/{page}"
        _controller: "News::list"
        _arguments:
          page: "@widget_0/currentPage"
      - routePath: "/tag/{tag_name}"
        _controller: "News::list"
        _arguments:
          tag_name: overwriteDemand/tags
      - routePath: "/{news_title}"
        _controller: "News::detail"
        _arguments:
          news_title: news
      - routePath: "/archive/{year}/{month}"
        _controller: "News::archive"
    defaultController: "News::list"
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
routes: {}
